[package]
name = "rcfe"
version = "0.1.0"
edition = "2024"

[lib]
[dependencies]
tokio = { version = "1.48.0", features = ["rt-multi-thread", "macros"] }
prost = "0.14.1"
tonic-prost = "0.14.2"
tonic = "0.14.2"
thiserror = "2.0.17"

[build-dependencies]
tonic-prost-build = "0.14.2"